### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by cgatian** [ealmansi/gqlz#1]
You can't use this in a localhost project due to CORs issues ⚰️. 

Im configuring Apollo with the following endpoint:
`https://graphqlzero.almansi.me/api`

![image](https://user-images.githubusercontent.com/1752170/64440082-57048b00-d099-11e9-8530-142aa0507f47.png)

**Comment by ealmansi** [comment]
Thanks for reporting this.

Will fix this ASAP and let you know.

**Comment by cgatian** [comment]
If it puts any urgency in it, im currently writing a medium post that features this as its sample endpoint. Kinda rough that it doesnt work so I might strip it from the post. Anyway, my incentive to getting this fixed would be getting exposure through my publication.

**Comment by cgatian** [comment]
https://medium.com/@Cgatian/configuring-a-angular-cli-project-with-graphql-37217f66d419

**Comment by ealmansi** [comment]
Hi @cgatian ,

This should be fixed now. Please let me know if you have any further issues.

Thanks again for bringing this up.
